### ISSUE TITLE
New edition for reference [Lilienthal, C. (December 2015)] available

### ISSUE THREAD

**Issue by StefanZoerner** [isaqb-org/curriculum-ddd#3]
A new edition for reference [Lilienthal, C. (December 2015)] available. 

In the curriculum:
* [Lilienthal, C. (December 2015)] Langlebige Software-Architekturen. dpunkt.verlag.

Current version;
* [Lilienthal, C. (December 2019)] Langlebige Software-Architekturen. 3rd edition, dpunkt.verlag.

Perhaps also an option to mention the English translation.

**Comment by hofstef** [comment]
done, [see](https://github.com/isaqb-org/curriculum-ddd/commit/2b5db1f71b021fa231e0c2b7ff3db90d4af413ab)
