### ISSUE TITLE
New edition for reference [Hruschka, P. (2014)] available

### ISSUE THREAD

**Issue by StefanZoerner** [isaqb-org/curriculum-ddd#4]
A new edition for reference [Hruschka, P. (2014)] is available.

In the curriculum:

* [Hruschka, P. (2014)] Business Analysis und Requirements Engineering. Carl Hanser, München.

Current version;

* [Hruschka, P. (2019)] Business Analysis und Requirements Engineering, Carl Hanser 2nd edition 2019

**Comment by hofstef** [comment]
Updated with #6
